core:
    modules:
        - detection
        - autopilot
        - telemetry
        - ugv
        - interop
    log_dir: logs
    config_save_interval: 60
autopilot:
    #s3
    serial_port: /dev/ttyAMA0
detection:
  colors_filename: "auxillary/RGB_Colors.txt"
  alphanumeric_model_filename: 'models/alphanumeric'
  shape_model_filename: 'models/shape'
telemetry:
    ground_ip: '127.0.0.1'
    port: 5005
    send_interval: 30
    receive_interval: 30
    buffer_size: 100
    max_packet_size: 170
