core:
    modules:
        - detection
        - autopilot
        - command_ingest
        - telemetry
        - ugv
    log_dir: logs
    config_save_interval: 60
autopilot:
    #s3
    serial_port: /dev/ttyAMA0
telemetry:
    ground_ip: '127.0.0.1'
    port: 5005
    send_interval: 30
    buffer_size: 100
    max_packet_size: 170
